export const PAYMENT_METHODS = [
  {
    id: "tng",
    name: "Touch n Go",
    icon: "/images/tngo.png",
    description: "Quick tap payment",
    color: "#0066CC",
  },
  {
    id: "cash",
    name: "Cash",
    icon: "/images/cash.png",
    description: "Pay with cash",
    color: "#28A745",
  },
  {
    id: "debit-credit",
    name: "Debit/Credit Card",
    icon: "/images/visa.png",
    description: "Card payment",
    color: "#FF6B35",
  },
];

export const IMAGE_MAP = {
  "roti-canai": "roti-canai.jpg",
  "roti-telur": "roti-telur.jpg",
  "roti-plain": "roti-plain.jpg",
  murtabak: "murtabak.jpg",
  "mee-goreng": "mee-goreng.jpg",
  "maggi-goreng": "maggi-goreng.jpg",
  "nasi-goreng": "nasi-goreng.jpg",
  "nasi-kandar": "nasi-kandar.jpg",
  "sup-kambing": "sup-kambing.jpg",
  "teh-tarik": "teh-tarik.jpg",
  "milo-ais": "milo-ais.jpg",
  "teh-ais-limau": "teh-ais-limau.jpg",
};

export const MENU_DATA = [
  {
    id: 1,
    name: "Roti Canai",
    category: "Roti (Flatbreads)",
    price: 3.5,
    cost: 1.2,
    description: "Flaky, crispy flatbread served with rich dhal and curry dips",
    image: "roti-canai",
  },
  {
    id: 2,
    name: "Roti Telur",
    category: "Roti (Flatbreads)",
    price: 4.0,
    cost: 1.5,
    description: "Savory roti stuffed with beaten egg and onions",
    image: "roti-telur",
  },
  {
    id: 3,
    name: "Roti Plain",
    category: "Roti (Flatbreads)",
    price: 2.5,
    cost: 0.8,
    description: "Simple, plain crispy flatbread",
    image: "roti-plain",
  },
  {
    id: 4,
    name: "Murtabak",
    category: "Roti (Flatbreads)",
    price: 6.5,
    cost: 2.5,
    description: "Thick stuffed pancake with minced meat, onions, and spices",
    image: "murtabak",
  },
  {
    id: 5,
    name: "Mee Goreng",
    category: "Goreng (Fried Noodles)",
    price: 6.0,
    cost: 2.0,
    description: "Yellow noodles in spicy tomato sauce with tofu and potatoes",
    image: "mee-goreng",
  },
  {
    id: 6,
    name: "Maggi Goreng",
    category: "Goreng (Fried Noodles)",
    price: 5.5,
    cost: 1.8,
    description: "Instant noodles stir-fried with vegetables, egg, and spices",
    image: "maggi-goreng",
  },
  {
    id: 7,
    name: "Nasi Goreng Mamak",
    category: "Rice Dishes",
    price: 7.0,
    cost: 2.5,
    description:
      "Signature wok-fried rice with smoky flavor, sambal, chicken, and egg",
    image: "nasi-goreng",
  },
  {
    id: 8,
    name: "Nasi Kandar",
    category: "Rice Dishes",
    price: 8.5,
    cost: 3.0,
    description:
      "Steamed rice with curries - choose from ayam goreng, squid, vegetables",
    image: "nasi-kandar",
  },
  {
    id: 9,
    name: "Sup Kambing",
    category: "Soups",
    price: 9.0,
    cost: 3.5,
    description:
      "Hearty, heavily spiced mutton soup served with roti benggali",
    image: "sup-kambing",
  },
  {
    id: 10,
    name: "Teh Tarik",
    category: "Drinks",
    price: 3.0,
    cost: 0.8,
    description:
      "Black tea mixed with condensed milk, pulled for a frothy head",
    image: "teh-tarik",
  },
  {
    id: 11,
    name: "Milo Ais",
    category: "Drinks",
    price: 3.5,
    cost: 1.0,
    description: "Popular iced chocolate-malt beverage",
    image: "milo-ais",
  },
  {
    id: 12,
    name: "Teh O Ais Limau",
    category: "Drinks",
    price: 2.5,
    cost: 0.6,
    description: "Iced black tea with sugar and fresh lime",
    image: "teh-ais-limau",
  },
];
